name: Build ZMK Firmware

on:
  push:
    paths:
      - '**.keymap'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ZMK Firmware
        uses: zmkfirmware/zephyr-action@v1
        with:
          manifest-path: 'modu-module/config'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modu-firmware
          path: build/zephyr/zmk.uf2
